this commit completes ticket_7_post_comments including testing and err…
cheesenbeans/BE-NEWS pull request #7
Opened 2023-05-11 10:40 UTC by cheesenbeans

…orhandling

2023-05-11 11:11 UTC, dappernerddesigns requested changes
Please keep an eye on your test descriptions. You shouldn't be copying them from old repos, you should be able to write a test block now. 

What happens if you try to add a comment to an article with a username that is not in the database? How would you check this and how could you handle this?

I would recommend moving your error handling into it's own file at some point, but this is not a deal breaker.

There is no update to the endpoints.json for this ticket, please update it.

Consider the comments and points above then please resubmit this ticket.

2023-05-11 11:11 UTC, dappernerddesigns commented on app.js
> +
As you're getting a lot of these now, it might be worth considering extracting them out into their own file 😄

2023-05-11 11:11 UTC, dappernerddesigns commented on app.test.js
> +  test("POST request status 400 responds with error status and message invalid restaurant ", () => {
🤨

2023-05-11 11:11 UTC, dappernerddesigns commented on app.test.js
> +});
You may need extra tests here to make sure that an existing user can post to the database. The seed file for comments is reliant on the username existing on the users table.

2023-05-11 12:59 UTC, HannahBurks requested changes
Almost there - we need a test for if the username is invalid - this should auto throw a PSQL error as it is a foreign key (if not referenced in other table throws error)

2023-05-11 12:59 UTC, HannahBurks commented on app.test.js
> +  test("POST request - status 201 responds with a new comment ", () => {
We also want to add another 201 test that tests it ignore all unnecessary proporties

2023-05-11 12:59 UTC, HannahBurks commented on app.test.js
>          expect(response.body.msg).toBe("Article Not Found!");
We also want to do a test when the username is not a preexisting one in the database - 404

2023-05-11 15:30 UTC, cjplatten commented
I can only see the 201 test on this commit, please add the 404 test and resubmit

2023-05-12 07:48 UTC, HannahBurks approved these changes
Merge away :) nice work

2023-05-12 08:21 UTC, merged